PYTHON_PATH = rf"C:\Users\Lenovo\Desktop\PROJECTS\PROGRAMMING\top_proper\sth-knowledge\venv\Scripts\python.exe"
MANAGE_PY = rf"C:\Users\Lenovo\Desktop\PROJECTS\PROGRAMMING\top_proper\sth-knowledge\source\less_Django\my_own_name\manage.py"

"""#######################################
VIEWS
#######################################"""
from django.http import HttpResponse
def my_custom_request_handler(request):
    return HttpResponse("We are inside code generated by external files.")

"""#######################################
MODEL workflow
#######################################"""
# from less_Django.external_code.scripts_ import run_command_line
# def commit_changes_in_app_models(app_name):
#     run_command_line([
#         PYTHON_PATH, MANAGE_PY, "makemigrations", app_name
#     ])
#
# def push_changes_in_ALL_models():
#     run_command_line([
#         PYTHON_PATH, MANAGE_PY, "migrate"
#     ])


"""#######################################
DATABASE API
#######################################"""
"""
1. SELECT (+WHERE)
2. JOIN 
3. INSERT
4. DELETE

https://docs.djangoproject.com/en/3.0/intro/tutorial02/#s-playing-with-the-api

"""


